In [5]:
def preprocessor(df1,date):
    import pandas as pd
    import numpy as np
    from sklearn import preprocessing

    df1.dropna(inplace=True)
    
    df1 = df1.reset_index()
    df1.drop(columns='index',inplace=True)
    
    
    df1=df1[df1['Sale.Type']=='Cash']
    df1 = df1.reset_index()
    df1.drop(columns='index',inplace=True)
    df1['Pstng.Date'] = pd.to_datetime(df1['Pstng.Date'],dayfirst=True).dt.strftime("%Y%m%d").astype(int)
    df1['Net.Due.Dt'] = pd.to_datetime(df1['Net.Due.Dt'],dayfirst=True).dt.strftime("%Y%m%d").astype(int)
    df1['Clearing'] = pd.to_datetime(df1['Clearing'],dayfirst=True).dt.strftime("%Y%m%d").astype(int)   
    df=df1[df1['Pstng.Date'] < date ]
    df3=df[df['Clearing'] > date] 
    df.drop(df[df['Clearing'] > date].index,inplace=True)
    df1=df
    df1 = df1.reset_index()
    df1.drop(columns='index',inplace=True)
    
    
    df3 = df3.reset_index()
    df3.drop(columns='index',inplace=True)
    
    
    df2=df1[['Pstng.Date','Net.Due.Dt','Clearing','Status']]
    df2.dropna(inplace=True)
    df2['Range of Delay']=pd.to_datetime(df2['Clearing'],format='%Y%m%d') - pd.to_datetime(df2['Net.Due.Dt'] , format='%Y%m%d')
    df2['PayT']= pd.to_datetime(df2['Net.Due.Dt'],format='%Y%m%d') - pd.to_datetime(df2['Pstng.Date'],format='%Y%m%d')
    df2['y2']=pd.to_datetime(df2['Clearing'],format='%Y%m%d') - pd.to_datetime(df2['Pstng.Date'] , format='%Y%m%d')
    df2['Range of Delay']=df2['Range of Delay'].dt.days
    df2['Range of Delay']=pd.to_numeric(df2['Range of Delay'])
    df2['PayT']=df2['PayT'].dt.days
    df2['PayT']=pd.to_numeric(df2['PayT'])
    df2['y2']=df2['y2'].dt.days
    df2['y2']=pd.to_numeric(df2['y2'])
    
    df2 = df2.reset_index()
    df2.drop(columns = 'index',inplace=True)
    
    df2['Status'] = np.where(df2['Range of Delay'] > 7, 2, (np.where(df2['Range of Delay'] > 0, 1,0)))#,(np.where(df2['Range of Delay'] < 0, 0, 1)))))#(np.where(df2['Range of Delay'] > 0, 1,0)))))#(np.where(df2['Range of Delay'] > 0, 1,0)))))#(np.where(df2['Range of Delay'] > 10, 2,(np.where(df2['Range of Delay'] > 0,1,0)))))))# (np.where(df2['Range of Delay'] > 30, 5, (np.where(df2['Range of Delay'] > 15, 4, (np.where(df2['Range of Delay'] > 7, 3, (np.where(df2['Range of Delay'] > 3, 2, (np.where(df2['Range of Delay'] > 0, 1 ,0)))))))))))))))
    df2['y2'] = np.where(df2['y2'] > 30, 3, (np.where(df2['y2'] > 15, 2,(np.where(df2['y2'] > 0, 1, 0)))))
    print('Ranges in the initial set')
    print(np.unique(df2['Status'],return_counts=True))
    print('----------------------------------------------------------------------------------------')
                         
    print('Y2 s in the initial set')
    print(np.unique(df2['y2'],return_counts=True))
    print('----------------------------------------------------------------------------------------')
    
    
    df1['Status']=df2['Status']
    df1['PayT']=df2['PayT']
    df1.dropna(inplace=True)
    y1=df1['Status']
    y2=df2['y2']
    
    busa = preprocessing.LabelEncoder()
    ccar = preprocessing.LabelEncoder()
    month = preprocessing.LabelEncoder()
    zone = preprocessing.LabelEncoder()
    bran = preprocessing.LabelEncoder()
    payt = preprocessing.LabelEncoder()
    
    df1.drop(columns='Status',inplace=True)
    #df1['Status']=df1['Status'].astype('category').cat.codes
    arr=busa.fit(df1['BusA'])
    df1['BusA']=busa.transform(df1['BusA'])
    arr=ccar.fit(df1['CCAr'])
    df1['CCAr']=ccar.transform(df1['CCAr'])#.astype('category').cat.codes
    #df1['Account']=df1['Account'].astype('category').cat.codes
    arr=month.fit(df1['Month'])
    df1['Month']=month.transform(df1['Month'])#.astype('category').cat.codes
    df1.drop(columns='Reference',inplace=True)
    df1.drop(columns='Customer.Name',inplace=True)
    df1.drop(columns=['DocumentNo','Year','Clrng.doc.'],inplace=True)
    arr=zone.fit(df1['Zone'])
    df1['Zone']=zone.transform(df1['Zone'])    #.astype('category').cat.codes
    arr=bran.fit(df1['Bran'])
    df1['Bran']=bran.transform(df1['Bran'])#.astype('category').cat.codes
    arr =payt.fit(df1['PayT'])
    #df1['PayT'] = payt.transform(df1['PayT'])#.astype('category').cat.codes
    df1.drop(columns='Doc.Chq.dt',inplace=True)
    df1.drop(columns='Ty',inplace=True)
    df1.drop(columns='Sale.Type',inplace=True)
    
    
    #df1.drop(columns='Clearing',inplace=True)
    df1 = df1.reset_index()
    df1.drop(columns='index',inplace=True)
    df1.drop(columns='Arr..Clearing...Net.Due.Date.',inplace=True)
    df1.drop(columns='G.L',inplace=True)
    df1.drop(columns='Clearing',inplace=True)
    

    
    
    #print('Creating Red Alert Zone')
    #table = pd.crosstab(columns=y, index=df1['Account'])
    #table.columns= ["No delay"," 0 - 10", ">10"]
    #print(table)
    #print(table.sort_values(['>10'],ascending=False).head())
    #arr=table.sort_values(['>10'],ascending=False)
    #arr.drop(columns=["No delay"," 0 - 10"],inplace=True)
    #df_1=arr[arr['>10']>40]
    #df_2=[]
    
    
    #df1['Account']=df1['Account']/100000
    #df1['Reference']=df1['Reference']/1000000000
    #df1['Pstng.Date']=df1['Pstng.Date']/100000000
    #df1['Net.Due.Dt']=df1['Pstng.Date']/100000000
    


    #print(df_1.index)
    
    
    ###################Oversampling##############################
    #from imblearn.over_sampling import ADASYN 
    #sm = ADASYN()
    #df4, y = sm.fit_resample(df1, y)
    #df1=pd.DataFrame(df4,columns=df1.columns)
    ############################################################
    
    #y1=df1.columns
    #x = df1.values #returns a numpy array
    #min_max_scaler = preprocessing.MinMaxScaler()
    #x_scaled = min_max_scaler.fit_transform(x)
    #df1 = pd.DataFrame(x_scaled,columns=df1.columns)
    
    
    return df1,df3,y1,y2,busa,ccar,month,zone,bran,payt

In [6]:
def trainer(df1,y1,y2):
    import pandas as pd
    import numpy as np
    from sklearn import metrics
    from sklearn.ensemble import RandomForestClassifier
    from sklearn import tree
    from sklearn import neighbors
    from sklearn.ensemble import AdaBoostClassifier
    from sklearn.ensemble import VotingClassifier
    from sklearn.ensemble import BaggingClassifier
    from sklearn.model_selection import train_test_split
    
    #y=np.array(df1['Status'])
    
    

    X=df1
    #df1.head(5)
    xtrain1, xtest1, ytrain1, ytest1 = train_test_split(X, y1, test_size = 0.3, random_state=30)
    xtrain2, xtest2, ytrain2, ytest2 = train_test_split(X, y2, test_size = 0.3, random_state=30)
    # Random forest Model: 
    model1= RandomForestClassifier(n_estimators = 300,random_state = 100, n_jobs=3, verbose=2, max_features=None)
    model2= RandomForestClassifier(n_estimators = 300,random_state = 100, n_jobs=3, verbose=2, max_features=None)#,class_weight={0:100,1:10000,2:500})

    eclf = model1
    
    #VotingClassifier(estimators=[ ('knn_bagging', bagging), ('adaboost', clf), ('RF',model)],voting='soft')
    eclf1 = eclf.fit(xtrain1, ytrain1)
    eclf1 = model2.fit(xtrain2,ytrain2)
    print('TRAINING DONE ......................')
    
    
    eclf1=eclf.predict(xtrain1)
    eclf2=eclf.predict(xtest1)
    print('TRAINING RESULTS-----------------------------------------')
    print("Accuracy: for Training for range :",metrics.accuracy_score(ytrain1, eclf1)*100)
    print("Accuracy: for Testing for range:",metrics.accuracy_score(ytest1, eclf2)*100)
    print()
    
    
    eclf3=model2.predict(xtrain2)
    eclf4=model2.predict(xtest2)
    print('TRAINING RESULTS-----------------------------------------')
    print("Accuracy: for Training for y2:",metrics.accuracy_score(ytrain2, eclf3)*100)
    print("Accuracy: for Testing for y2 :",metrics.accuracy_score(ytest2, eclf4)*100)
    print()
    
    print('Confusion Matrix for Range')
    print(metrics.confusion_matrix(eclf2, ytest1))
    print()
    print('Confusion Matrix for Range')
    print(metrics.confusion_matrix(eclf4, ytest2))
    print()
    print('--------------------------------------------------------------------------------------------------------------------')
    return eclf,model2

In [7]:
def predict(df1,clf1,clf2,busa,ccar,month,zone,bran,payt):
    import numpy as np
    import pandas as pd
    import copy
    from sklearn import preprocessing
    df=copy.deepcopy(df1)
    print(df.shape)
    #df['Prediction']=np.zeros(len(df1))
    print(df1.shape)
    df1.dropna(inplace=True)
    df1 = df1.reset_index()
    df1.drop(columns='index',inplace=True)
    #df1['Status']=df1['Status'].astype('category').cat.codes)
    #df1['Status']=df1['Status'].astype('category').cat.codes
    
    df1['PayT']= pd.to_datetime(df1['Net.Due.Dt'],format='%Y%m%d') - pd.to_datetime(df1['Pstng.Date'],format='%Y%m%d')
    df1['PayT']=df1['PayT'].dt.days
    df1['PayT']=pd.to_numeric(df1['PayT'])
    df1.drop(columns='Clearing',inplace=True)
    df1 = df1.reset_index()
    df1.drop(columns = 'index',inplace=True)
    #df1['Status']=df1['Status'].astype('category').cat.codes
    df1['BusA']=busa.transform(df1['BusA'])
    df1['CCAr']=ccar.transform(df1['CCAr'])#.astype('category').cat.codes
    #df1['Account']=df1['Account'].astype('category').cat.codes
    df1['Month']=month.transform(df1['Month'])#.astype('category').cat.codes
    df1.drop(columns='Reference',inplace=True)
    df1.drop(columns='Customer.Name',inplace=True)
    df1.drop(columns=['DocumentNo','Year'],inplace=True)
    df1['Zone']=zone.transform(df1['Zone'])#.astype('category').cat.codes
    df1['Bran']=bran.transform(df1['Bran'])#.astype('category').cat.codes
    #df1['PayT'] =payt.transform(df1['PayT'])#.astype('category').cat.codes
    df1.drop(columns='Doc.Chq.dt',inplace=True)
    df1.drop(columns='Ty',inplace=True)
    df1.drop(columns='Sale.Type',inplace=True)
    #df1['Pstng.Date']=pd.to_datetime(df1['Pstng.Date'],dayfirst=True).dt.strftime("%Y%m%d").astype(int)
    #df1['Net.Due.Dt']=pd.to_datetime(df1['Net.Due.Dt'],dayfirst=True).dt.strftime("%Y%m%d").astype(int)
    #df1['Clearing']=pd.to_datetime(df1['Clearing']).dt.strftime("%Y%m%d").astype(str)
    #df1.drop(columns=['Net.Due.Dt','Clearing'],inplace=True)
    #df1.drop(columns='Net.Due.Dt',inplace=True)
    df1 = df1.reset_index()
    df1.drop(columns='index',inplace=True)
    df1.drop(columns='Arr..Clearing...Net.Due.Date.',inplace=True)
    df1.drop(columns='G.L',inplace=True)
    
    #y1=df1.columns
    #x = df1.values #returns a numpy array
    #min_max_scaler = preprocessing.MinMaxScaler()
    #x_scaled = min_max_scaler.fit_transform(x)
    #df1 = pd.DataFrame(x_scaled,columns=df1.columns)
    
    #df1['Account']=df1['Account']/100000
    #df1['Reference']=df1['Reference']/1000000000
    #df1['Pstng.Date']=df1['Pstng.Date']/100000000
    #df1['Net.Due.Dt']=df1['Pstng.Date']/100000000
    
    
    print('Starting Prediction ....')
    prediction=clf1.predict(df1)
    print('Generating Probabilities.....')
    predictprob=clf1.predict_proba(df1)
    print('Finished prediction...')
    print()

    print('Starting Prediction 2....')
    prediction1=clf2.predict(df1)
    print('Generating Probabilities 2.....')
    predictprob1=clf2.predict_proba(df1)
    print('Finished prediction 2...')
    print()
    #df['Probability']=np.zeros(len(df))
    #df['Probability']=np.zeros(len(df))
    print(df1.head())

    arr=['No Delay','Low Delay','High Delay']
    arr1=['Low Delay_on_NetDUE','Medium Delay_on_NetDUE','High Delay_on_NetDUE']
    arr2=['Low Delay_on_Pstng','Low Medium Delay_on_Pstng','High Delay_on_Pstng','Very High Delay_on_Pstng']#,'High Delay']#,'30 to 180','>180']#,'8-15 days','16-30 days','31-60 days','61-90 days','90-180 days','>180 days']
    for i in range(len(arr)):
        df[arr1[i]]=np.empty(len(df))
    print('Computing Prediction Table............')
    df['Actual'] = (pd.to_datetime(df['Clearing'],format='%Y%m%d')-pd.to_datetime(date,format='%Y%m%d')).dt.days
    df['Actual'] = pd.to_numeric(df['Actual'])
    df['Prediction_on_NetDue'] = prediction
    df['Prediction_on_Pstng'] = prediction1
    #df['Prediction']=np.where(df['Prediction'] == 0, 'No Delay',(np.where(df['Prediction'] == 1, 'Low Delay',(np.where(df['Prediction'] == 2, 'High Delay','')))))
    for i in range(len(arr1)):
        df[arr1[i]]=np.around(predictprob[:,i],decimals=2)
        df[arr2[i]]=np.around(predictprob1[:,i],decimals=2)
    print(df.head(5))
    
    
    days=np.where((df['Prediction_on_Pstng']==0)&(df['Low Delay_on_Pstng']>0.9),1,
                   (np.where((df['Prediction_on_Pstng']==0)&(df['Low Delay_on_Pstng']>0.8),2,
                   (np.where((df['Prediction_on_Pstng']==0)&(df['Low Delay_on_Pstng']>0.7),3,
                   (np.where((df['Prediction_on_Pstng']==0)&(df['Low Delay_on_Pstng']>0.6),4,
                   (np.where((df['Prediction_on_Pstng']==0)&(df['Low Delay_on_Pstng']>0.4),5,
                   (np.where((df['Prediction_on_Pstng']==0)&(df['Low Medium Delay_on_Pstng']>0.2),6,          
                   (np.where((df['Prediction_on_Pstng']==1)&(df['Low Delay_on_Pstng']>0.4),8,
                   (np.where((df['Prediction_on_Pstng']==1)&(df['Low Delay_on_Pstng']>0.3),9,
                   (np.where((df['Prediction_on_Pstng']==1)&(df['Low Medium Delay_on_Pstng']>0.5),10,
                   (np.where((df['Prediction_on_Pstng']==1)&(df['Low Medium Delay_on_Pstng']>0.6),11,
                   (np.where((df['Prediction_on_Pstng']==1)&(df['Low Medium Delay_on_Pstng']>0.7),13,
                   (np.where((df['Prediction_on_Pstng']==1)&(df['Low Medium Delay_on_Pstng']>0.8),15,
                   (np.where((df['Prediction_on_Pstng']==2)&(df['Low Medium Delay_on_Pstng']>0.45),16,
                   (np.where((df['Prediction_on_Pstng']==2)&(df['Low Medium Delay_on_Pstng']>0.4),18,
                   (np.where((df['Prediction_on_Pstng']==2)&(df['Low Medium Delay_on_Pstng']>0.3),20,
                   (np.where((df['Prediction_on_Pstng']==2)&(df['High Delay_on_Pstng']>0.7),22,
                   (np.where((df['Prediction_on_Pstng']==2)&(df['High Delay_on_Pstng']>0.75),30,
                    (np.where((df['Prediction_on_Pstng']==3)&(df['High Delay_on_Pstng']>0.45),35,
                    (np.where((df['Prediction_on_Pstng']==3)&(df['High Delay_on_Pstng']>0.35),45,
                    (np.where((df['Prediction_on_Pstng']==3)&(df['High Delay_on_Pstng']>0.25),50,60
                            )))))))))))))))))))))))))))))))))))))))
    
    
    
    days1=np.where(df['Prediction_on_NetDue']==0,1,np.where(df['Prediction_on_NetDue']==1,5,np.where(df['Prediction_on_NetDue']==2,30,60)))#,60)))
    crr=(pd.to_datetime(df1['Pstng.Date'],format='%Y%m%d')+ pd.to_timedelta(days, unit='D')-pd.to_datetime(date,format='%Y%m%d')).dt.days.astype(int)
    crr=df[(crr<5) & (crr>-7)]
    crr['Payment']='Yes'
    arr=(pd.to_datetime(df1['Net.Due.Dt'],format='%Y%m%d')+ pd.to_timedelta(days1, unit='D')-pd.to_datetime(date,format='%Y%m%d')).dt.days.astype(int)
    brr=df[(arr<5) & (arr>-7)]
    brr['Payment']='Yes'
    print('ARR =')
    print(brr.head())
    print('BRR =')
    print(crr.head())
    
    #df['When']=np.where(brr['Prediction_on_NetDue'] < 2 ,'PAYMENT EXPECTED SOON',np.where(brr[''])
    df6 = pd.merge(crr, brr, how='outer', on=list(crr.columns))
    df_out = pd.merge(df,df6,how='outer',on=list(df.columns))
    
    #df['Difference']=pd.to_datetime(df['Clearing'],format='%Y%m%d') - pd.to_datetime(df['Pstng.Date'],format='%Y%m%d')
    print('DF=')
    print(df_out.head())
    print('Writing to csv file')
    print('-----------------------------------------------------------------------------------------')
    df_out.to_csv('Predictedout_Nov_01.csv',index=False)
    return days

In [8]:
# import time
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import copy
trainpath='MyData.csv'


print('Reading data...')
df1=pd.read_csv(trainpath)
print('Finished Reading...')
print()
print(df1.head(5))
print()
date=20181101
df3=copy.deepcopy(df1)
print('Preprocessing started .......')
df2,df4,y1,y2,busa,ccar,month,zone,bran,payt=preprocessor(df1,date)
print(df2.head(5))
print('Preprocessing Done...........')
print('--------------------------------------------------------------------------------------------------------')

Reading data...
Finished Reading...

   BusA CCAr     Reference  Account          Customer.Name   Zone  Bran  Ty  \
0  1000  BPR  4.132000e+09   929488      KAUSALYA AGENCIES  South  SBAD  RV   
1  9600  BPR  1.115502e+09   928860  TATA STEEL PROCESSING  North  GBAD  RV   
2  9600  BPR  1.115502e+09   928860  TATA STEEL PROCESSING  North  GBAD  RV   
3  1000  BPR  2.412166e+09   928860  TATA STEEL PROCESSING  North  GBAD  RV   
4  2500  BPR  2.410320e+09   928860  TATA STEEL PROCESSING  North  GBAD  RV   

    Status  Local.Crcy.Amt  ...  Doc.Chq.dt Month Pstng.Date  Net.Due.Dt  \
0   Not OD            0.10  ...  31.12.2018   Dec   31-12-18    05-01-19   
1  Overdue            0.04  ...  31.10.2018   Oct   31-10-18    10-11-18   
2   Not OD            0.12  ...  05.11.2018   Nov   05-11-18    15-11-18   
3  Overdue            0.17  ...  30.12.2018   Dec   30-12-18    09-01-19   
4  Overdue            0.16  ...  03.11.2018   Nov   03-11-18    13-11-18   

       G.L  Year Clrng.doc.  Cl

In [9]:
df4.drop(columns=['Status','Clrng.doc.'],inplace=True)

In [10]:
import time
t1=time.time()
print('Training Starting............')
clf1,clf2=trainer(df2,y1,y2)
print('Training Done...................')
print('Time Taken',time.time()-t1)
print('-----------------------------------------------------------------------------------')

Training Starting............


[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.


building tree 1 of 300building tree 2 of 300
building tree 3 of 300

building tree 4 of 300
building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300
building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300
building tree 15 of 300
building tree 16 of 300
building tree 17 of 300
building tree 18 of 300building tree 19 of 300

building tree 20 of 300
building tree 21 of 300
building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300
building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300


[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    2.4s


building tree 38 of 300
building tree 39 of 300
building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300
building tree 47 of 300
building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300building tree 54 of 300

building tree 55 of 300
building tree 56 of 300
building tree 57 of 300
building tree 58 of 300
building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300building tree 66 of 300

building tree 67 of 300
building tree 68 of 300
building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79

[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:   11.0s


building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300
building tree 178 of 300building tree 179 of 300

building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300
building tree 197 of 300
building tree 198 of 300
building tree 199 of 300
building tree 200 of 300


[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:   20.0s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.


building tree 1 of 300building tree 2 of 300
building tree 3 of 300

building tree 4 of 300
building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300
building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300
building tree 15 of 300
building tree 16 of 300
building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300
building tree 21 of 300
building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300
building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300
building tree 38 of 300
building tree 39 of 300


[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    2.2s


building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300building tree 47 of 300

building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300
building tree 57 of 300
building tree 58 of 300
building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300building tree 63 of 300

building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300building tree 68 of 300

building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300building tree 80 of 300

building tree 81

[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:    9.7s


building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300building tree 173 of 300

building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300
building tree 178 of 300
building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300
building tree 197 of 300
building tree 198 of 300
building tree 199 of 300


[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:   19.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.


TRAINING DONE ......................


[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    0.3s
[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:    1.6s
[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:    3.7s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    0.2s
[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:    1.2s
[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:    3.6s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.


TRAINING RESULTS-----------------------------------------
Accuracy: for Training for range : 99.19642857142857
Accuracy: for Testing for range: 96.29310344827586



[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    0.7s
[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:    2.9s
[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:    6.4s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    0.2s
[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:    1.4s
[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:    2.5s finished


TRAINING RESULTS-----------------------------------------
Accuracy: for Training for y2: 99.20258620689654
Accuracy: for Testing for y2 : 96.35775862068967

Confusion Matrix for Range
[[12399   258    29]
 [  201   939    12]
 [   11     5    66]]

Confusion Matrix for Range
[[12398   279     8     0]
 [  204  1001     4     0]
 [    9     3    13     0]
 [    0     0     0     1]]

--------------------------------------------------------------------------------------------------------------------
Training Done...................
Time Taken 57.16426944732666
-----------------------------------------------------------------------------------


In [17]:
print('Feature Importances')
for feature in zip(df2.columns, clf1.feature_importances_,clf2.feature_importances_):
    print(feature)

Feature Importances
('BusA', 0.020466153653252057, 0.030423471898192406)
('CCAr', 0.0, 0.0)
('Account', 0.1607347575721318, 0.12850169221247343)
('Zone', 0.04078607776293827, 0.015736713430687447)
('Bran', 0.0907845376283726, 0.07421848915819487)
('Local.Crcy.Amt', 0.07148721441657234, 0.10690093121390926)
('PayT', 0.06105458253106924, 0.12090124838664766)
('Month', 0.01983321535415464, 0.03006367454145746)
('Pstng.Date', 0.10810390854532877, 0.13398361559566963)
('Net.Due.Dt', 0.15361123988521033, 0.13027004122578592)
('Pending_Amy', 0.17934046766912753, 0.14661756552469493)
('pending_cnt', 0.09379784498184245, 0.08238255681228698)


In [18]:
testpath= ''
days=predict(df4,clf1,clf2,busa,ccar,month,zone,bran,payt)
print() 
print('______________________________________  END  ____________________________________')
print()
print()

(61, 22)
(61, 22)
Starting Prediction ....
Generating Probabilities.....


[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:    0.0s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:    0.0s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:    0.0s


Finished prediction...

Starting Prediction 2....
Generating Probabilities 2.....


[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:    0.0s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 156 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 300 out of 300 | elapsed:    0.0s finished


Finished prediction 2...

   BusA  CCAr  Account  Zone  Bran  Local.Crcy.Amt  PayT  Month  Pstng.Date  \
0     1     0   856737     0    10            0.16     4      5    20180929   
1     1     0   856737     0    10            0.11     4      5    20180929   
2     1     0   117556     2     1            0.05     2      5    20180930   
3     1     0   117556     2     1            0.10     2      5    20180930   
4     1     0   117556     2     1            0.07     2      5    20180930   

   Net.Due.Dt  Pending_Amy  pending_cnt  
0    20181003         0.28            2  
1    20181003         0.28            2  
2    20181002         0.25            1  
3    20181002         0.25            1  
4    20181002         0.25            1  
Computing Prediction Table............
   BusA CCAr     Reference  Account                   Customer.Name   Zone  \
0  2000  BPR  2.438085e+09   856737  BAJRANG STEEL (SALES) CORPORAT   East   
1  2000  BPR  2.438085e+09   856737  BAJRANG STEEL (