In [27]:
import pandas as pd
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import numpy as np

In [28]:
df=pd.read_excel('BPR Only .xlsx','Sheet1')

In [29]:
#df.head()

In [30]:
df['Account'].count()

117472

In [31]:
#df.shape

In [32]:
df.dropna(inplace=True)

In [33]:
#df.shape

In [34]:
#df['Account'].apply(pd.value_counts)

In [35]:
#df=df[df.Account == (115806 or 928860) ]

In [36]:
df.shape

(113712, 19)

In [37]:
#df.head()

In [38]:
#df.drop(columns=['    BusA','CCAr','Zone','Bran'],inplace=True)

In [39]:
df['Status']=df['Status'].astype('category').cat.codes
df['    BusA']=df['    BusA'].astype('category').cat.codes
df['CCAr']=df['CCAr'].astype('category').cat.codes
#df['Account']=df['Account'].astype('category').cat.codes
df.drop(columns='Reference',inplace=True)
df.drop(columns='Customer Name',inplace=True)
df.drop(columns=['DocumentNo','Month','Year','Clrng doc.'],inplace=True)
df['Zone']=df['Zone'].astype('category').cat.codes
df['Bran']=df['Bran'].astype('category').cat.codes
df['PayT'] = df['PayT'].astype('category').cat.codes

In [40]:
df.drop(columns='Doc/Chq dt',inplace=True)
df.head(5)#df.drop(columns=['Reference','Account','DocumentNo','Doc/Chq dt','Year','Clrng doc.'],inplace=True)

BusA  CCAr  Account  Zone  Bran  Status    Local Crcy Amt  \
0         6     0   928860     1     9       1          0.035212   
1         6     0   928860     1     9       0          0.123124   
2         6     0   814077     1     9       1          0.274466   
4         6     0   814077     1     9       1          0.151648   
5         6     0   814077     1     9       1          0.156470   

   Arr (Clearing - Net Due Date)  PayT Pstng Date Net Due Dt   Clearing  
0                              5    31 2018-10-31 2018-11-10 2018-11-15  
1                              0    31 2018-11-05 2018-11-15 2018-11-15  
2                              3    27 2018-11-19 2018-11-24 2018-11-27  
4                              6    27 2018-12-29 2019-01-03 2019-01-09  
5                              6    27 2018-12-29 2019-01-03 2019-01-09

In [41]:
#df.shape

In [42]:
#df.drop(columns='Customer Name',inplace=True)

In [43]:
#df.shape

In [44]:
#df.head()

In [45]:
#df['Status']=df['Status'].astype('category')

In [46]:
#df["Status"] = df["Status"].cat.codes

In [47]:
#df.head()

In [48]:
#df['Status'].value_counts()

In [49]:
#df

In [54]:
df['Pstng Date']=df['Pstng Date'].dt.strftime("%Y%m%d").astype(str)
df['Net Due Dt']=df['Net Due Dt'].dt.strftime("%Y%m%d").astype(str)
df['Clearing']=df['Clearing'].dt.strftime("%Y%m%d").astype(str)

AttributeError: Can only use .dt accessor with datetimelike values

In [51]:
#df

In [53]:
df = df.reset_index()
df.drop(columns='index',inplace=True)
#df.to_excel('Reduced.xlsx')

In [52]:
df['Arr (Clearing - Net Due Date)'].value_counts()

 0     75383
 1      7625
-1      7395
 2      4512
-2      3418
 3      2626
 4      1776
 5      1515
-3      1315
 6      1242
 7       834
-4       768
 8       647
 9       642
-5       515
 10      355
-6       324
-10      295
 11      284
-7       260
-9       235
-8       222
 12      211
 13      209
 15      158
 14      146
 16      127
 19       94
 17       85
-11       76
 23       54
 22       49
 18       48
 20       43
-12       41
 21       26
 28       24
 25       18
 27       18
 26       17
-13       17
 24       16
 29        9
-19        7
-14        6
-15        6
 34        5
-87        3
-89        3
 31        2
 40        1
-18        1
 47        1
-16        1
-53        1
-42        1
Name: Arr (Clearing - Net Due Date), dtype: int64

In [198]:

############################   START FROM HERE   ###############################################

#df=pd.read_excel('Reduced.xlsx')

In [199]:
#Training Model

In [55]:
df.drop(columns='Clearing',inplace=True)
df.drop(columns='Arr (Clearing - Net Due Date)',inplace=True)

In [56]:
from sklearn.ensemble import RandomForestClassifier

In [58]:

from sklearn import preprocessing
y=df.columns
x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled,columns=df.columns)
df.head(5)


C:\Users\Laptop\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


BusA  CCAr   Account      Zone      Bran  Status    Local Crcy Amt  \
0       1.0   0.0  0.999243  0.333333  0.409091     1.0          0.069108   
1       1.0   0.0  0.999243  0.333333  0.409091     0.0          0.241670   
2       1.0   0.0  0.860825  0.333333  0.409091     1.0          0.538742   
3       1.0   0.0  0.860825  0.333333  0.409091     1.0          0.297662   
4       1.0   0.0  0.860825  0.333333  0.409091     1.0          0.307127   

       PayT  Pstng Date  Net Due Dt  
0  0.861111    0.759036    0.072875  
1  0.861111    0.848193    0.073389  
2  0.750000    0.865060    0.074314  
3  0.750000    0.997590    0.997225  
4  0.750000    0.997590    0.997225

In [59]:
y=np.array(df['Status'])
X=df
#df.drop(columns='Month',inplace=True)


In [60]:
y

array([1., 0., 1., ..., 1., 1., 1.])

In [61]:
df.drop(columns='Status',inplace=True)

In [62]:
df.shape

(113712, 9)

In [80]:
X=df
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.3)#X[:],X[100000:],y[:100000],y[100000:]##

In [81]:
model= RandomForestClassifier(n_estimators=100, n_jobs=2, random_state=0)

In [82]:
y1=model.fit(xtrain, ytrain)

In [85]:

#np.asarray(arr)
#np.savetxt("OUTPUT_COMPARISON.csv", arr, delimiter=",")


In [83]:
y2=model.predict(xtest)

In [94]:
from sklearn import metrics
from sklearn.metrics import roc_auc_score
print("Accuracy:",metrics.accuracy_score(ytest, y2))
print('ROC SCORE:',roc_auc_score(ytest, y2))

Accuracy: 0.9511051181333177
ROC SCORE: 0.9164886511122873


In [95]:
print(pd.Series(model.feature_importances_,index=df.columns).sort_values(ascending=False))
print(metrics.confusion_matrix(ytest, y2))

Account             0.196448
Net Due Dt          0.194054
Pstng Date          0.179761
  Local Crcy Amt    0.144507
PayT                0.111159
Bran                0.095008
    BusA            0.044651
Zone                0.034413
CCAr                0.000000
dtype: float64
[[26351   652]
 [ 1016  6095]]


In [86]:
unique, counts = np.unique(ytest, return_counts=True)
dict(zip(unique, counts))

{0.0: 27003, 1.0: 7111}

In [96]:
unique, counts = np.unique(y2, return_counts=True)
dict(zip(unique, counts))

{0.0: 27367, 1.0: 6747}

In [87]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression(multi_class='ovr')
logisticRegr.fit(xtrain, ytrain)
y4=logisticRegr.predict(xtest)
print("Accuracy:",metrics.accuracy_score(ytest, y4))

C:\Users\Laptop\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy: 0.7949229055519728


In [98]:
unique, counts = np.unique(ytest, return_counts=True)
dict(zip(unique, counts))


{0.0: 27003, 1.0: 7111}

In [99]:
unique, counts = np.unique(y2, return_counts=True)
dict(zip(unique, counts))

{0.0: 27367, 1.0: 6747}

In [92]:
coefficients=logisticRegr.coef_
for i in range(len(X.columns)):
    print(X.columns[i],'-------->',coefficients[0][i])

    BusA --------> -0.09087713457460764
CCAr --------> 0.0
Account --------> 0.5435903674093082
Zone --------> -0.05797169654421662
Bran --------> 1.085674161623357
  Local Crcy Amt --------> -0.5528034196671171
PayT --------> 2.1641936803727955
Pstng Date --------> 0.8794817944822487
Net Due Dt --------> 1.0278655085911572


In [89]:
#print(metrics.confusion_matrix(ytest, y2))
print(metrics.confusion_matrix(ytest, y4))

[[26198   805]
 [ 6191   920]]


In [90]:
unique, counts = np.unique(y4, return_counts=True)
dict(zip(unique, counts))

{0.0: 32389, 1.0: 1725}

In [106]:
from sklearn.metrics import average_precision_score
print('Random Forest' ,average_precision_score(ytest, y2))
print('Logistic Regression',average_precision_score(ytest,y4))

Random Forest 0.804076738569967
Logistic Regression 0.2504808225283149


In [103]:
'''from sklearn.metrics import precision_recall_curve

from inspect import signature

precision, recall, _ = precision_recall_curve(ytest, y2)

# In matplotlib < 1.5, plt.fill_between does not have a 'step' argument
step_kwargs = ({'step': 'post'}
               if 'step' in signature(plt.fill_between).parameters
               else {})
plt.step(recall, precision, color='b', alpha=0.2,
         where='post')
plt.fill_between(recall, precision, alpha=0.2, color='b', **step_kwargs)

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.ylim([0.0, 1.05])
plt.xlim([0.0, 1.0])
plt.title('2-class Precision-Recall curve: AP={0:0.2f}'.format(
          average_precision))'''


"from sklearn.metrics import precision_recall_curve\n\nfrom inspect import signature\n\nprecision, recall, _ = precision_recall_curve(ytest, y2)\n\n# In matplotlib < 1.5, plt.fill_between does not have a 'step' argument\nstep_kwargs = ({'step': 'post'}\n               if 'step' in signature(plt.fill_between).parameters\n               else {})\nplt.step(recall, precision, color='b', alpha=0.2,\n         where='post')\nplt.fill_between(recall, precision, alpha=0.2, color='b', **step_kwargs)\n\nplt.xlabel('Recall')\nplt.ylabel('Precision')\nplt.ylim([0.0, 1.05])\nplt.xlim([0.0, 1.0])\nplt.title('2-class Precision-Recall curve: AP={0:0.2f}'.format(\n          average_precision))"

In [ ]:
####################   NEWER ALGO    ######################

In [ ]:
model.fit(df1[:100000], ytrain)
yp=model.predict(df1[100000:])
print("Accuracy:",metrics.accuracy_score(ytest, yp))

In [ ]:
df=df[df.Account == (115806 or 928860) ]